### ISSUE TITLE
Library HSPI

### ISSUE THREAD

**Issue by anlpereira** [G6EJD/ESP32-and-how-to-use-ILI9341-TFT-Display#2]
Hi, I've tested this code running ok on an ESP32 board with an ILI9341 LCD Display. But now I want to add SD card to it, so I need to use software SPI to control the LCD and SPI to Read from SD card. But, the software SPI is to slow. So, do you have some solution? Thanks

**Comment by G6EJD** [comment]
The sd card interface is wired in parallel (for example on most ili9341 boards with the display) and all you need is another pin for SDCard chip select, that way your programme can select either display or SD card. Same for the touch interface then there would be 3 chip select pins needed. You find the CS for the SD card even you SD.begin(CS);
